#include "core/package_draft.h"
#include "package_summary_test_fixture.h"

#include <QCoreApplication>
#include <QDir>
#include <QElapsedTimer>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>
#include <iostream>
#include <limits>

using namespace vibestudio;
namespace {
bool expect(bool value, const char* message)
{
	if (!value) { std::cerr << message << '\n'; } return value;
}
bool overflow(const QDir& root)
{
	bool ok = true; QString error;
	constexpr auto maximum = std::numeric_limits<quint64>::max();
	auto source = std::make_shared<tests::SummaryReader>();
	source->add("a.bin", maximum); source->add("b.bin", 0); source->add("folder", maximum, true);
	PackageArchive archive;
	ok &= expect(archive.loadSnapshot(source, &error) && archive.summary().totalSizeBytes == maximum
		&& !archive.summary().totalSizeOverflow && archive.summary().fileCount == 2 && archive.summary().directoryCount == 1,
		"Exact UINT64_MAX totals remain valid; directory metadata contributes no payload bytes.");
	const auto original = archive;
	source->rows[1].sizeBytes = 1;
	ok &= expect(archive.loadSnapshot(source, &error) && archive.summary().totalSizeOverflow && archive.summary().totalSizeBytes == maximum
		&& !original.summary().totalSizeOverflow && source->payloadReads == 0,
		"Overflow is explicit and saturated; an independent prior snapshot retains its exact summary without payload reads.");
	archive.clear(); ok &= expect(archive.summary().entryCount == 0 && !archive.summary().totalSizeOverflow, "Clear invalidates archive summary and overflow state.");
	const QString first = root.filePath("large.zip"), second = root.filePath("extra.zip"), shadow = root.filePath("shadow.zip");
	ok &= expect(tests::summaryZip(first, {{"a.bin", maximum}}) && tests::summaryZip(second, {{"b.bin", 1}})
		&& tests::summaryZip(shadow, {{"a.bin", 2}}), "Create bounded independent ZIP metadata fixtures.");
	PackageArchiveSession session;
	ok &= expect(session.openPrimaryArchive(first, &error) && session.summary().totalSizeBytes == maximum && !session.summary().totalSizeOverflow,
		"Disk reader and one-layer session preserve the exact maximum declared size.");
	ok &= expect(session.mountArchive(second, {}, &error) && session.summary().totalSizeOverflow, "Merged layer totals flag overflow across individually valid sources.");
	const auto overflowing = session;
	ok &= expect(session.mountArchive(shadow, {}, &error) && !session.summary().totalSizeOverflow && session.summary().totalSizeBytes == 3
		&& overflowing.summary().totalSizeOverflow, "Shadowing recomputes the winning-entry total without changing an older session snapshot.");
	ok &= expect(session.popMountedLayer() && session.summary().totalSizeOverflow && session.popMountedLayer()
		&& !session.summary().totalSizeOverflow && session.summary().totalSizeBytes == maximum, "Layer removal invalidates cached size and overflow state.");
	session.clear(); ok &= expect(session.summary().entryCount == 0 && session.summary().totalSizeBytes == 0, "Cleared session has no stale cached metadata.");
	PackageStagingModel plan; PackageArchive owned;
	ok &= expect(owned.loadSnapshot(source, &error) && plan.loadBaseArchive(owned, &error) && plan.summary().totalsAvailable && plan.summary().beforeSizeOverflow
		&& plan.summary().afterSizeOverflow && !plan.summary().canSave && plan.summary().blockingCount == 1
		&& plan.beforeComposition().first().sizeOverflow && plan.afterComposition().first().sizeOverflow,
		"Staging retains readable metadata while marking overflowing totals/buckets and blocking export.");
	PackageWriteRequest request; request.destinationPath = root.filePath("never-written.zip"); request.dryRun = true;
	ok &= expect(!plan.writeArchive(request).succeeded() && !QFileInfo::exists(request.destinationPath) && source->payloadReads == 0,
		"Overflowing output is refused before payload reads or destination creation.");
	ok &= expect(plan.deleteEntry("b.bin", &error) && plan.summary().beforeSizeOverflow && !plan.summary().afterSizeOverflow
		&& plan.summary().afterBytes == maximum && plan.summary().canSave && plan.summary().deletedCount == 1,
		"Removing the excess entry recovers a saveable plan while before totals remain explicitly oversized.");
	ok &= expect(plan.undo() && plan.summary().afterSizeOverflow && !plan.summary().canSave && plan.redo()
		&& !plan.summary().afterSizeOverflow && plan.summary().canSave, "Undo and redo cannot retain stale summary or conflict state.");
	return ok;
}
bool history(const QDir& root)
{
	bool ok = true; QString error; PackageStagingModel plan;
	ok &= expect(plan.createEmpty(PackageArchiveFormat::Pk3) && plan.addBytes("abc", "one/a.txt", &error), "Prepare generated summary fixture.");
	const auto original = plan;
	ok &= expect(plan.summary().totalsAvailable && plan.summary().afterBytes == 3 && plan.summary().addedCount == 1, "Generated bytes have exact cached totals.");
	plan.beginOperationGroup("Change composition");
	ok &= expect(plan.addBytes("xy", "two/b.bin", &error) && plan.createDirectory("empty", &error)
		&& plan.endOperationGroup(true, &error) && plan.summary().afterBytes == 5 && plan.summary().addedCount == 3
		&& plan.summary().stagedDirectoryCount == 1 && plan.afterComposition().size() == 2, "Grouped edits update bytes, explicit directory counts and distinct composition buckets.");
	ok &= expect(plan.renameDirectory("two", "moved", &error) && plan.afterComposition().at(1).id.startsWith("moved:")
		&& original.summary().afterBytes == 3 && original.afterComposition().size() == 1, "Folder rename changes cached location labels and preserves independent snapshots.");
	ok &= expect(plan.undo() && plan.afterComposition().at(1).id.startsWith("two:"), "Undo refreshes cached composition identity.");
	const auto manifest = QJsonDocument::fromJson(plan.manifestJson(&error)).object();
	const auto summary = manifest.value("summary").toObject();
	ok &= expect(summary.value("totalsAvailable").toBool() && summary.value("afterBytesExact").toString() == "5"
		&& !summary.value("afterSizeOverflow").toBool(), "Manifest reports exact decimal totals with availability and overflow state.");
	const QString draft = root.filePath("history.vibepackage"); PackageStagingModel reopened;
	ok &= expect(PackageDraft::save(draft, &plan, false, &error) && PackageDraft::load(draft, &reopened, &error)
		&& reopened.summary().afterBytes == 5 && reopened.redo() && reopened.afterComposition().at(1).id.startsWith("moved:"),
		"Reopened drafts recompute summaries and retain redo semantics.");
	plan.clear(); ok &= expect(plan.summary().afterBytes == 0 && !plan.summary().canSave && plan.afterComposition().isEmpty(), "Clear releases summary and composition state.");
	return ok;
}
bool preparation()
{
	bool ok = true; QString error; auto owner = std::make_shared<tests::SummaryReader>(); auto& source = *owner;
	for (int index = 0; index < 5000; ++index) { source.add(QStringLiteral("folder-%1/a.txt").arg(index), 7); }
	PackageStagingModel plan; PackageArchive owned;
	ok &= expect(owned.loadSnapshot(owner, &error) && plan.loadBaseArchive(owned, &error), "Prepare metadata-only scale fixture.");
	bool stop = false, reached = false; PackageReadControl control;
	control.isCancelled = [&] { return stop; };
	control.progress = [&](const QString& phase, qint64 done, qint64) {
		if (phase == "Preparing package summaries" && done >= 256) { reached = stop = true; }
	};
	ok &= expect(!plan.preparePlan(&error, control) && reached && error.contains("cancelled") && source.payloadReads == 0,
		"Cancellation interrupts summary/bucket preparation without reading payloads or publishing a partial result.");
	ok &= expect(plan.preparePlan(&error) && plan.summary().afterBytes == 35000 && plan.afterComposition().size() == 5000,
		"Cancelled statistics can be retried to produce a complete summary and all buckets.");
	const auto before = plan.beforeComposition(), after = plan.afterComposition(); const int listings = source.listings;
	QElapsedTimer elapsed; elapsed.start(); quint64 checked = 0;
	for (int index = 0; index < 10000; ++index) {
		checked += plan.summary().afterBytes;
		ok &= plan.beforeComposition().constData() == before.constData() && plan.afterComposition().constData() == after.constData();
	}
	ok &= expect(checked == 350000000 && source.listings == listings && source.payloadReads == 0, "Repeated status/graph access shares the prepared metadata without relisting or payload work.");
	std::cout << "10000 summary/composition reads for 5000 files: " << elapsed.elapsed() << " ms\n";
	return ok;
}
}

int main(int argc, char** argv)
{
	QCoreApplication app(argc, argv); QTemporaryDir temporary; if (!temporary.isValid()) { return 1; }
	const QDir root(temporary.path()); const bool a = overflow(root), b = history(root), c = preparation();
	return a && b && c ? 0 : 1;
}
