#include "core/package_draft.h"
#include "core/package_staging.h"

#include <QCoreApplication>
#include <QDir>
#include <QElapsedTimer>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>

#include <iostream>

using namespace vibestudio;

namespace {
bool expect(bool condition, const char* message)
{
	if (!condition) { std::cerr << message << '\n'; }
	return condition;
}
bool write(const QString& path, const QByteArray& bytes)
{
	QFile file(path); return file.open(QIODevice::WriteOnly) && file.write(bytes) == bytes.size();
}
QByteArray read(const QString& path)
{
	QFile file(path); return file.open(QIODevice::ReadOnly) ? file.readAll() : QByteArray();
}
QByteArray entry(const PackageStagingModel& model, const QString& path)
{
	QByteArray bytes; QString error;
	const PackageStagingArchive reader(model);
	if (!reader.readEntryBytes(path, &bytes, &error)) { std::cerr << error.toStdString() << '\n'; }
	return bytes;
}
bool generated()
{
	bool ok = true; QString error; PackageStagingContentUsage usage;
	PackageStagingContentLimits limits; limits.maximumGeneratedBytes = 6;
	PackageStagingModel model(limits);
	ok &= expect(model.createEmpty(PackageArchiveFormat::Zip, {}, &error)
		&& model.addBytes("abc", "a", &error) && model.addBytes("def", "b", &error), "Admit generated bytes exactly at the shared boundary.");
	const PackageStagingArchive held(model);
	const auto revision = model.revision();
	ok &= expect(model.contentUsage(&usage, &error) && usage.generatedBytes == 6, "Current and history references share the same generated storage charge.");
	ok &= expect(!model.addBytes("x", "c", &error) && !error.isEmpty() && model.revision() == revision
		&& model.operations().size() == 2 && entry(model, "b") == "def", "Rejected generated admission preserves revision, plan and history.");
	ok &= expect(model.undo() && model.contentUsage(&usage, &error) && usage.generatedBytes == 6, "Redo retains its generated content charge.");
	const auto undone = model.revision();
	ok &= expect(!model.addBytes("four", "c", &error) && model.canRedo() && model.revision() == undone,
		"Rejected branch edits must preserve redo.");
	ok &= expect(model.addBytes("ghi", "c", &error) && !model.canRedo() && model.contentUsage(&usage, &error)
		&& usage.generatedBytes == 6 && entry(model, "c") == "ghi", "A successful branch can reuse the released redo allowance.");
	QByteArray bytes;
	ok &= expect(held.readEntryBytes("b", &bytes, &error) && bytes == "def", "Older immutable readers keep their independently owned content.");
	ok &= expect(model.deleteEntry("a", &error) && !model.addBytes("x", "d", &error), "Deleting a visible asset does not release bytes still retained by its operation/history.");
	const auto report = QJsonDocument::fromJson(model.manifestJson(&error)).object().value("summary").toObject().value("retainedContent").toObject();
	ok &= expect(report.value("generatedBytes").toString() == "6" && report.value("maximumGeneratedBytes").toString() == "6",
		"Manifest diagnostics expose exact retained content usage and policy.");

	PackageStagingModel group(limits);
	ok &= expect(group.createEmpty(PackageArchiveFormat::Zip) && group.addBytes("abc", "before") && group.undo(), "Prepare group cancellation with existing redo.");
	group.beginOperationGroup("Group");
	ok &= expect(group.addBytes("xy", "group") && !group.addBytes("zz", "refused", &error)
		&& group.contentUsage(&usage, &error) && usage.generatedBytes == 5, "Open groups retain both cancellation state and new bytes.");
	group.endOperationGroup(false);
	ok &= expect(group.canRedo() && group.redo() && entry(group, "before") == "abc"
		&& group.contentUsage(&usage, &error) && usage.generatedBytes == 3, "Cancelling a group releases its bytes and restores redo.");

	PackageStagingModel committed(limits);
	ok &= expect(committed.createEmpty(PackageArchiveFormat::Zip) && committed.addBytes("abc", "before") && committed.undo(), "Prepare group commit with existing redo.");
	committed.beginOperationGroup("Committed");
	ok &= expect(committed.addBytes("xy", "group") && committed.contentUsage(&usage, &error) && usage.generatedBytes == 5, "Inspect content before group commit.");
	committed.endOperationGroup();
	ok &= expect(committed.contentUsage(&usage, &error) && usage.generatedBytes == 2 && committed.addBytes("four", "after", &error),
		"Committing a group releases discarded redo before the next content admission.");

	limits.maximumGeneratedBytes = 3;
	PackageStagingModel raw(limits);
	char buffer[] = {'a', 'b', 'c'};
	ok &= expect(raw.createEmpty(PackageArchiveFormat::Zip) && raw.addBytes(QByteArray::fromRawData(buffer, 3), "raw", &error), "Stage a non-owning QByteArray view.");
	buffer[0] = 'z';
	ok &= expect(entry(raw, "raw") == "abc", "The accepted asset must own independent bytes after its caller changes raw storage.");
	PackageStagingModel smaller(PackageStagingContentLimits{2, PackageStagingContentLimits::fingerprintCeiling});
	ok &= expect(smaller.createEmpty(PackageArchiveFormat::Zip) && smaller.addBytes("x", "keep"), "Create a smaller destination model.");
	const auto beforeAdoption = smaller.revision();
	ok &= expect(!smaller.loadBaseArchive(PackageStagingArchive(raw), &error) && smaller.revision() == beforeAdoption
		&& entry(smaller, "keep") == "x", "Snapshot rebasing cannot replace the destination with over-limit content.");

	PackageStagingModel evicted(PackageStagingContentLimits{1, PackageStagingContentLimits::fingerprintCeiling});
	ok &= expect(evicted.createEmpty(PackageArchiveFormat::Zip) && evicted.addBytes("x", "gone"), "Create a history-only payload.");
	ok &= expect(evicted.clearOperation(evicted.operations().first().id), "Unstage the generated asset.");
	for (int index = 0; index < 256; ++index) { ok &= expect(evicted.addBytes({}, QStringLiteral("empty%1").arg(index), &error), "Advance bounded history."); }
	ok &= expect(evicted.addBytes("y", "new", &error) && evicted.contentUsage(&usage, &error) && usage.generatedBytes == 1,
		"Evicting the final history reference releases the generated allowance.");
	return ok;
}
bool batchAdmission()
{
	constexpr int count = 5000;
	PackageStagingModel model(PackageStagingContentLimits{count, PackageStagingContentLimits::fingerprintCeiling});
	QString error; PackageStagingContentUsage usage; QElapsedTimer elapsed; elapsed.start();
	if (!model.createEmpty(PackageArchiveFormat::Zip, {}, &error)) { return false; }
	// Evict old history with small edits, then use the production bulk-import
	// contract for the large batch. Retained bytes must include both parts.
	constexpr int historyEntries = 257;
	for (int index = 0; index < count; ++index) {
		if (index == historyEntries && !model.beginOperationGroup("Asset batch", &error)) { return false; }
		if (!model.addBytes("x", QStringLiteral("asset%1").arg(index), &error)) { std::cerr << error.toStdString() << '\n'; return false; }
	}
	if (!model.endOperationGroup(true, &error)) { std::cerr << error.toStdString() << '\n'; return false; }
	const auto revision = model.revision();
	bool ok = expect(model.operations().size() == count && model.contentUsage(&usage, &error) && usage.generatedBytes == count
		&& !model.addBytes("x", "refused", &error) && model.revision() == revision,
		"A large batch remains fully charged after its undo steps are evicted, and cannot admit an extra byte.");
	int undone = 0; while (model.undo()) { ++undone; }
	ok &= expect(undone == 256 && model.operations().size() == historyEntries - 255
		&& model.contentUsage(&usage, &error) && usage.generatedBytes == count && model.canRedo(),
		"All surviving groups undo exactly once and their redo payloads remain charged.");
	std::cout << "Retained-content admission: " << count << " assets in " << elapsed.elapsed() << " ms (debug observation, not a latency threshold)." << '\n';
	return ok;
}
bool fingerprints(const QDir& root)
{
	bool ok = true; QString error; PackageStagingContentUsage usage;
	const auto large = root.filePath("two-chunks.bin"), small = root.filePath("one-chunk.bin");
	ok &= expect(write(large, QByteArray(65537, 'a')) && write(small, "b"), "Create source fingerprint boundaries.");
	PackageStagingContentLimits limits; limits.maximumFingerprintBytes = 64;
	PackageStagingModel model(limits);
	ok &= expect(model.createEmpty(PackageArchiveFormat::Zip) && model.addFile(large, "a", &error, PackageStageConflictResolution::Block, {}, PackageFileImportMode::VerifyOnly)
		&& model.contentUsage(&usage, &error) && usage.fingerprintBytes == 64, "A staged file consumes its rounded chunk hash bytes once.");
	int reads = 0; PackageReadControl control; control.progress = [&](const QString&, qint64, qint64) { ++reads; };
	const auto revision = model.revision();
	ok &= expect(!model.addFile(small, "b", &error, PackageStageConflictResolution::Block, control, PackageFileImportMode::VerifyOnly)
		&& reads == 0 && model.revision() == revision && model.operations().size() == 1, "Fingerprint refusal precedes source reads and preserves the model.");
	ok &= expect(model.undo() && model.contentUsage(&usage, &error) && usage.fingerprintBytes == 64, "Redo source hashes remain charged.");
	ok &= expect(model.addFile(small, "b", &error, PackageStageConflictResolution::Block, {}, PackageFileImportMode::VerifyOnly)
		&& model.contentUsage(&usage, &error) && usage.fingerprintBytes == 32 && !model.canRedo(), "A successful branch releases unreachable source hashes.");
	control.isCancelled = [] { return true; }; reads = 0;
	const auto beforeCancel = model.revision();
	ok &= expect(!model.addFile(small, "cancelled", &error, PackageStageConflictResolution::Block, control, PackageFileImportMode::VerifyOnly)
		&& reads == 0 && model.revision() == beforeCancel, "Cancelled admission cannot start reads or accept an edit.");

	// Grow the file after the outer preflight but before capture snapshots its
	// metadata. The cancellation hook provides a deterministic boundary probe.
	const QString growingPath = root.filePath("growing.bin");
	PackageStagingModel growing(PackageStagingContentLimits{6, 32});
	ok &= expect(write(growingPath, "g") && growing.createEmpty(PackageArchiveFormat::Zip)
		&& growing.addBytes("k", "keep") && growing.contentUsage(&usage, &error), "Prepare source growth at capture admission.");
	int checks = 0, growthReads = 0; bool grew = false;
	PackageReadControl growthControl;
	growthControl.isCancelled = [&] { if (++checks == 2) { grew = write(growingPath, QByteArray(65537, 'g')); } return false; };
	growthControl.progress = [&](const QString&, qint64, qint64) { ++growthReads; };
	const auto beforeGrowth = growing.revision();
	ok &= expect(!growing.addFile(growingPath, "grown", &error, PackageStageConflictResolution::Block, growthControl, PackageFileImportMode::VerifyOnly)
		&& grew && growthReads == 0 && !error.isEmpty() && growing.revision() == beforeGrowth && growing.operations().size() == 1
		&& entry(growing, "keep") == "k", "A late fingerprint limit failure must reject the edit, not append an unreadable staged operation.");

	const QString basePath = root.filePath("base");
	ok &= expect(root.mkpath("base") && write(QDir(basePath).filePath("source"), "s"), "Create an on-disk base.");
	PackageArchive archive;
	limits.maximumFingerprintBytes = 32;
	PackageStagingModel base(limits);
	ok &= expect(archive.load(basePath, &error) && base.loadBaseArchive(archive, &error) && base.contentUsage(&usage, &error)
		&& usage.fingerprintBytes == 32, "The on-disk base shares the model's fingerprint budget.");
	ok &= expect(base.deleteEntry("source", &error) && !base.addFile(small, "new", &error, PackageStageConflictResolution::Block, {}, PackageFileImportMode::VerifyOnly),
		"A hidden base still retains its source fingerprints.");
	return ok;
}
bool drafts(const QDir& root)
{
	bool ok = true; QString error; PackageStagingContentUsage usage;
	const auto path = root.filePath("content.vibepackage");
	PackageStagingContentLimits limits; limits.maximumFingerprintBytes = 32;
	PackageStagingModel model(limits);
	ok &= expect(model.createEmpty(PackageArchiveFormat::Zip) && model.addBytes("same", "a") && model.addBytes("same", "b"), "Prepare generated content with a shared draft object identity.");
	ok &= expect(PackageDraft::save(path, &model, false, &error) && model.contentUsage(&usage, &error)
		&& usage.generatedBytes == 0 && usage.fingerprintBytes == 32, "Draft conversion releases generated bytes and charges each shared object once.");
	const auto manifestPath = QDir(path).filePath("document.json");
	const auto manifest = read(manifestPath);
	PackageStagingModel loaded(limits);
	ok &= expect(PackageDraft::load(path, &loaded, &error) && loaded.contentUsage(&usage, &error) && usage.fingerprintBytes == 32
		&& entry(loaded, "a") == "same" && entry(loaded, "b") == "same", "Draft load deduplicates fingerprint storage shared by multiple operations/history references.");
	limits.maximumFingerprintBytes = 31;
	PackageStagingModel rejected(limits);
	ok &= expect(rejected.createEmpty(PackageArchiveFormat::Zip) && rejected.addBytes("k", "keep"), "Prepare a destination that cannot admit the draft object.");
	int objectReads = 0; PackageReadControl control;
	control.progress = [&](const QString& source, qint64, qint64) { if (source.contains("/objects/")) { ++objectReads; } };
	const auto previousRevision = rejected.revision();
	ok &= expect(!PackageDraft::load(path, &rejected, &error, control) && objectReads == 0 && rejected.revision() == previousRevision
		&& entry(rejected, "keep") == "k" && read(manifestPath) == manifest, "Over-limit draft capture fails before payload hashing and preserves both documents.");
	ok &= expect(model.addBytes("different", "c", &error), "Generated content can remain staged while a draft storage conversion is reviewed.");
	const auto pending = model.revision();
	const auto files = QDir(QDir(path).filePath("objects")).entryList(QDir::Files);
	ok &= expect(!PackageDraft::save(path, &model, true, &error, {}, true) && !error.isEmpty()
		&& !PackageDraft::save(path, &model, true, &error) && read(manifestPath) == manifest && model.revision() == pending
		&& entry(model, "c") == "different" && QDir(QDir(path).filePath("objects")).entryList(QDir::Files) == files,
		"Dry and real draft saves reject over-limit conversion without publishing objects/metadata or discarding pending edits.");
	return ok;
}
} // namespace

int main(int argc, char** argv)
{
	QCoreApplication app(argc, argv);
	QTemporaryDir temporary;
	if (!temporary.isValid()) { return 1; }
	bool ok = generated();
	ok &= batchAdmission();
	ok &= fingerprints(QDir(temporary.path()));
	ok &= drafts(QDir(temporary.path()));
	for (const auto limits : {PackageStagingContentLimits{-1, 0}, PackageStagingContentLimits{0, -1},
		PackageStagingContentLimits{PackageStagingContentLimits::generatedCeiling + 1, 0},
		PackageStagingContentLimits{0, PackageStagingContentLimits::fingerprintCeiling + 1}}) {
		PackageStagingModel invalid(limits); QString error;
		ok &= expect(!invalid.createEmpty(PackageArchiveFormat::Zip, {}, &error) && !error.isEmpty() && !invalid.isLoaded(), "Invalid API limits cannot raise ceilings or create a partial document.");
	}
	return ok ? 0 : 1;
}
