#pragma once

#include "core/asset_tools.h"
#include "core/audio_markers.h"

#include <functional>

namespace vibestudio
{

class PackageStagingModel;

// Interleaved floating point samples. Frame ranges are [first, end), shared by
// the editor and CLI; samples are quantized only for integer-format delivery.
inline constexpr qint64 AudioSampleLimit = 16 * 1024 * 1024;
inline constexpr qint64 AudioInputByteLimit = 128 * 1024 * 1024;

struct AudioClip {
	int channels = 0;
	int sampleRate = 0;
	QVector<float> samples;
	AudioMarkers markers{};
	[[nodiscard]] qint64 frameCount() const;
	[[nodiscard]] qint64 durationMs() const;
};

struct AudioWorkControl {
	std::function<bool()> cancelled;
};

struct AudioClipResult {
	AudioClip clip;
	QString error;
	bool cancelled = false;
	QStringList warnings{};
	[[nodiscard]] bool succeeded() const
	{
		return error.isEmpty() && !cancelled && clip.channels > 0 && clip.sampleRate > 0;
	}
};

struct AudioEdit {
	// trim, delete, silence, reverse, fade-in/out, gain, normalize, mono/stereo,
	// invert, remove-dc. Channel conversions apply to the entire sound.
	QString operation;
	qint64 firstFrame = 0;
	qint64 endFrame = -1;  // -1 means the end of the clip.
	double decibels = 0.0; // gain, or the target peak for normalize.
};

QString validateAudioClip(const AudioClip& clip, bool allowEmpty = false);
// Canonical existing paths, absolute paths otherwise; respects platform case rules.
bool audioPathsReferToSameFile(const QString& first, const QString& second);
// Native WAV/DMX plus bounded device-independent MP3, FLAC and Vorbis import.
// PC speaker tone sequences and unsupported compressed codecs fail explicitly.
AudioClipResult decodeAudioClip(const QString& sourceName, const QByteArray& bytes,
                                const AudioWorkControl& control = {});
AudioClipResult applyAudioEdit(const AudioClip& clip, const AudioEdit& edit, const AudioWorkControl& control = {});
// Empty clips are valid working documents; encoded playback/delivery still
// requires samples. Paste requires matching rates/channels, without implicit SRC.
AudioClipResult createAudioClip(int sampleRate, int channels, qint64 frames = 0, const AudioWorkControl& control = {});
AudioClipResult replaceAudioRange(const AudioClip& clip, qint64 first, qint64 end, const AudioClip& insertion,
                                  const AudioWorkControl& control = {});
// Adds every source frame at first, extending the target if needed. Float
// headroom is retained, and the caller may normalize before integer export.
AudioClipResult mixAudioClip(const AudioClip& clip, qint64 first, const AudioClip& source,
                             const AudioWorkControl& control = {});
AudioClipResult insertAudioSilence(const AudioClip& clip, qint64 first, qint64 frames,
                                   const AudioWorkControl& control = {});
AssetAudioPeaks audioClipPeaks(const AudioClip& clip, int buckets = 2048);
QByteArray encodeAudioWav(const AudioClip& clip, QString* error = nullptr);
// Atomic file save. Existing files require overwrite, and source paths can be
// protected even when overwrite is requested.
bool saveAudioWav(const AudioClip& clip, const QString& path, bool overwrite, const QString& protectedPath,
                  QString* error = nullptr, bool dryRun = false);
// Generated bytes belong to the normal staging plan; nothing is written to
// the source archive until the user saves that plan through Packages.
bool stageAudioWav(const QByteArray& wav, const QString& virtualPath, PackageStagingModel* staging, bool replace,
                   QString* error = nullptr);

} // namespace vibestudio
